/* eslint-disable */
/**
 * AUTO-GENERATED by web/scripts/codegen.mjs from schemas/ontology/assertion.schema.json —
 * do not edit; run `npm run codegen` after a schema change.
 */

export type Attribute = string | null;
export type Description = string;
export type Id = string;
export type BusinessDays = boolean;
export type Days = number;
/**
 * The assertion type determines what evidence *can* prove it.
 */
export type AssertionType = "STATE" | "EVENT" | "SEQUENCE" | "AGGREGATE" | "EXISTENCE" | "NON-EXISTENCE" | "TIMING";

/**
 * A lettered, typed, testable attribute of a claim. The type
 * constrains admissible evidence; TIMING must say its window.
 */
export interface Assertion {
  attribute?: Attribute;
  description: Description;
  id: Id;
  timing?: TimingConstraint | null;
  type: AssertionType;
}
export interface TimingConstraint {
  business_days?: BusinessDays;
  days: Days;
}
