/* eslint-disable */
/**
 * AUTO-GENERATED by web/scripts/codegen.mjs from schemas/ontology/capability_entry.schema.json —
 * do not edit; run `npm run codegen` after a schema change.
 */

/**
 * @minItems 1
 */
export type AccessModes = [AccessMode, ...AccessMode[]];
export type AccessMode = "direct-api" | "official-mcp" | "community-mcp" | "custom-adapter" | "playwright";
export type AuthScope = string;
export type HistoryCaveats = string[];
export type Id = string;
/**
 * @minItems 1
 */
export type JoinKeys = [string, ...string[]];
/**
 * D-L1 (RATIFIED): ratification IS the freeze — one lifecycle for
 * collection specs, capability entries, and manifest snapshots.
 */
export type LifecycleState = "draft" | "frozen" | "superseded";
export type ExhaustionMethod = string;
export type PaginationMethod = "cursor" | "page" | "none";
/**
 * @minItems 1
 */
export type PopulationsYielded = [YieldedPopulation, ...YieldedPopulation[]];
/**
 * @minItems 1
 */
export type Attributes = [string, ...string[]];
export type Description = string;
export type PopulationType = "entity" | "event" | "relationship";
/**
 * @minItems 1
 */
export type Citations = [string, ...string[]];
export type DocVersion = string | null;
export type ResearchedAt = string;
export type ResearchedBy = string;
export type RateLimits = string | null;
export type RatifiedBy = string | null;
export type Surface = string;
export type System = string;
export type Cadence = string | null;
export type TemporalKind = "state-only" | "event-history" | "full-history" | "snapshot-cadence";
export type WindowDays = number | null;

export interface CapabilityEntry {
  access_modes: AccessModes;
  auth_scope: AuthScope;
  history_caveats?: HistoryCaveats;
  id: Id;
  join_keys: JoinKeys;
  lifecycle?: LifecycleState;
  pagination: Pagination;
  populations_yielded: PopulationsYielded;
  provenance: Provenance;
  rate_limits?: RateLimits;
  ratified_by?: RatifiedBy;
  surface: Surface;
  system: System;
  temporal: TemporalCoverage;
}
export interface Pagination {
  exhaustion_method: ExhaustionMethod;
  method: PaginationMethod;
}
export interface YieldedPopulation {
  attributes: Attributes;
  description: Description;
  type: PopulationType;
}
/**
 * Who researched this, when, from what documentation — citations are
 * the Cartographer's whole authority (it maps, never annexes).
 */
export interface Provenance {
  citations: Citations;
  doc_version?: DocVersion;
  researched_at: ResearchedAt;
  researched_by: ResearchedBy;
}
export interface TemporalCoverage {
  cadence?: Cadence;
  kind: TemporalKind;
  window_days?: WindowDays;
}
