/* eslint-disable */
/**
 * AUTO-GENERATED by web/scripts/codegen.mjs from schemas/ontology/delta.schema.json —
 * do not edit; run `npm run codegen` after a schema change.
 */

/**
 * Set-based reconciliation buckets — counts are diagnostics, never
 * evidence.
 */
export type DeltaBucket = "intersection" | "left_only" | "right_only" | "conflict" | "unresolvable" | "excluded";
export type Owner = string;
export type Rationale = string | null;
/**
 * Every substrate answer resolves to one of these; nothing exits
 * silently — N/A demands a rationale (enforced on DispositionRecord).
 */
export type DispositionValue =
  "implemented" | "inherited" | "shared" | "vendor_managed" | "compensating" | "not_applicable";
export type MemberRef = string;
export type Owner1 = string | null;

/**
 * A reconciliation difference as a first-class object with an owner
 * and a disposition — never just a count.
 */
export interface Delta {
  bucket: DeltaBucket;
  disposition?: DispositionRecord | null;
  member_ref: MemberRef;
  owner?: Owner1;
}
/**
 * Nothing exits silently: NOT_APPLICABLE demands a rationale.
 */
export interface DispositionRecord {
  owner: Owner;
  rationale?: Rationale;
  value: DispositionValue;
}
