/* eslint-disable */
/**
 * AUTO-GENERATED by web/scripts/codegen.mjs from schemas/ontology/evidence_quality_contract.schema.json —
 * do not edit; run `npm run codegen` after a schema change.
 */

export type AuthContext = string;
export type CollectorVersion = string;
export type ContractHash = string;
export type Endpoint = string;
export type Id = string;
export type PopulationRef = string;
export type FailureMode = string;
export type Method = string;
export type SchemaVersion = string;
export type Source = string;
/**
 * @minItems 1
 */
export type SupportedAssertionTypes = [AssertionType, ...AssertionType[]];
/**
 * The assertion type determines what evidence *can* prove it.
 */
export type AssertionType = "STATE" | "EVENT" | "SEQUENCE" | "AGGREGATE" | "EXISTENCE" | "NON-EXISTENCE" | "TIMING";
export type Tenant = string;
export type End = string;
export type Start = string;

/**
 * Full identity plus the five properties; a contract declares which
 * assertion types it is entitled to support (invariant: no PASS unless
 * the evidence is fit to prove the claim).
 */
export interface EvidenceQualityContract {
  auth_context: AuthContext;
  collector_version: CollectorVersion;
  contract_hash: ContractHash;
  endpoint: Endpoint;
  id: Id;
  parameters?: Parameters;
  population_ref: PopulationRef;
  quality: EvidenceQuality;
  schema_version: SchemaVersion;
  source: Source;
  supported_assertion_types: SupportedAssertionTypes;
  tenant: Tenant;
  time_window: TimeWindow;
}
export interface Parameters {
  [k: string]: string;
}
export interface EvidenceQuality {
  integrity: QualityProperty;
  population: QualityProperty;
  provenance: QualityProperty;
  semantics: QualityProperty;
  temporal_validity: QualityProperty;
}
/**
 * One of the five EQC properties: an independent named method with an
 * independent failure mode.
 */
export interface QualityProperty {
  failure_mode: FailureMode;
  method: Method;
}
/**
 * Temporal semantics are part of evidence identity (invariant: no
 * evidence without provenance and temporal semantics).
 */
export interface TimeWindow {
  end: End;
  start: Start;
}
