/* eslint-disable */
/**
 * AUTO-GENERATED by web/scripts/codegen.mjs from schemas/ontology/population.schema.json —
 * do not edit; run `npm run codegen` after a schema change.
 */

export type Ref = string;
export type SourceRole = "authoritative" | "contributing" | "corroborating" | "discovery" | "exclusion";
export type System = string;
export type Definition = string;
/**
 * Set-based reconciliation buckets — counts are diagnostics, never
 * evidence.
 */
export type DeltaBucket = "intersection" | "left_only" | "right_only" | "conflict" | "unresolvable" | "excluded";
export type Owner = string;
export type Rationale = string | null;
/**
 * Every substrate answer resolves to one of these; nothing exits
 * silently — N/A demands a rationale (enforced on DispositionRecord).
 */
export type DispositionValue =
  "implemented" | "inherited" | "shared" | "vendor_managed" | "compensating" | "not_applicable";
export type MemberRef = string;
export type Owner1 = string | null;
export type Deltas = Delta[];
export type Description = string;
/**
 * @minItems 1
 */
export type Sources = [SourceRef, ...SourceRef[]];
export type Exclusions = string[];
export type Id = string;
export type Name = string;
export type End = string;
export type Start = string;
export type Size = number | null;
/**
 * The assurance-state ladder. Coverage is never computed against a
 * denominator left of RATIFIED.
 */
export type AssuranceState = "UNDEFINED" | "DEFINED" | "DISCOVERED" | "RECONCILED" | "RATIFIED" | "STALE";
export type PopulationType = "entity" | "event" | "relationship";

/**
 * Invariant: no population without a derivation rule (general case)
 * or an authoritative source (degenerate case) — exactly one.
 */
export interface Population {
  authoritative_source?: SourceRef | null;
  definition: Definition;
  deltas?: Deltas;
  derivation_rule?: DerivationRule | null;
  exclusions?: Exclusions;
  id: Id;
  name: Name;
  period: TimeWindow;
  size?: Size;
  state?: AssuranceState;
  type: PopulationType;
}
export interface SourceRef {
  ref: Ref;
  role: SourceRole;
  system: System;
}
/**
 * A reconciliation difference as a first-class object with an owner
 * and a disposition — never just a count.
 */
export interface Delta {
  bucket: DeltaBucket;
  disposition?: DispositionRecord | null;
  member_ref: MemberRef;
  owner?: Owner1;
}
/**
 * Nothing exits silently: NOT_APPLICABLE demands a rationale.
 */
export interface DispositionRecord {
  owner: Owner;
  rationale?: Rationale;
  value: DispositionValue;
}
export interface DerivationRule {
  description: Description;
  sources: Sources;
}
/**
 * Temporal semantics are part of evidence identity (invariant: no
 * evidence without provenance and temporal semantics).
 */
export interface TimeWindow {
  end: End;
  start: Start;
}
