/* eslint-disable */
/**
 * AUTO-GENERATED by web/scripts/codegen.mjs from schemas/verdict-record.schema.json —
 * do not edit; run `npm run codegen` after a schema change.
 */

/**
 * One population-scoped control verdict with its full audit trail. Conventions forked from GRCEngClub finding.schema.json v1.0.0 (knowledge/01_corpus/05_prior_art/Aegis_Prior_Art_GRCEngClub_Toolkit.md §3.1): const-pinned schema_version, closed objects, conditional requirements, the source/source_version/run_id/collected_at reproducibility tuple, severity independent of status. Deltas per docs/EVALUATION.md §2: record_hash + chain_prev, population_id/population_count/completeness_ref, spec_id + spec_hash, test_function_version, ratification_ref, and unknown_cause as the required companion of UNKNOWN. Verdict vocabulary and UNKNOWN why-codes follow the ratified rulings docs/DECISIONS.md D-V1 and D-U1 (PRD-v3 §2). skipped is deliberately absent: a population-testing system has no skip state that is not either EXCLUDED or a completeness failure. Hand-authored for the first milestone; superseded by the pydantic-generated schemas when SCH01 lands (D-P1).
 */
export type AegisSentinelVerdictRecord = {
  [k: string]: unknown;
} & {
  /**
   * const-pinned semver; consumers pin a major version
   */
  schema_version: "0.1.0";
  record_id: string;
  /**
   * Control identifier from the testing library, e.g. CM-03
   */
  control_id: string;
  /**
   * The five ratified verdict states (docs/DECISIONS.md D-V1, PRD-v3 §2): EXCLUDED is the former NOT_APPLICABLE and keeps its ratification_ref requirement; EXCEPTION is a dispositioned legitimate exception and requires disposition_ref
   */
  status: "PASS" | "FAIL" | "UNKNOWN" | "EXCLUDED" | "EXCEPTION";
  /**
   * Required companion of status=UNKNOWN. PRD-v3 why-codes per docs/DECISIONS.md D-U1; D-7 cause families map in as basis_missing→UNKNOWN_EVIDENCE, identity_fuzzy→UNKNOWN_POPULATION, no_basis_anywhere→UNKNOWN_TESTABILITY
   */
  unknown_cause?:
    "UNKNOWN_DISCOVERY" | "UNKNOWN_OWNER" | "UNKNOWN_POPULATION" | "UNKNOWN_EVIDENCE" | "UNKNOWN_TESTABILITY";
  message?: string;
  /**
   * Independent of status: a passing critical control still tells the consumer the stakes
   */
  severity?: "critical" | "high" | "medium" | "low" | "informational";
  /**
   * FAIL and UNKNOWN verdicts must carry support; PASS may be terse
   */
  support?: {
    field_values: {};
    record_hashes: string[];
  };
  source: string;
  source_version: string;
  run_id: string;
  /**
   * RFC 3339; the pattern enforces the shape because format alone is annotation-only in most validators
   */
  collected_at: string;
  /**
   * SHA-256 of the evidence record at intake (D-1)
   */
  record_hash: string;
  /**
   * Hash-chain link to the previous record; null only for the first record in a chain
   */
  chain_prev: string | null;
  population_id: string;
  population_count: number;
  /**
   * Pointer to the completeness assertion for the population this verdict is scoped to
   */
  completeness_ref: string;
  spec_id: string;
  /**
   * Hash of the frozen collection spec that produced the record: run_id says when, spec_hash says under what ratified plan
   */
  spec_hash: string;
  /**
   * Version of the pure function that emitted the verdict, with its seeded-fixture reference
   */
  test_function_version: string;
  /**
   * Pointer to the hashed human sign-off; required when status=EXCLUDED (D-V1)
   */
  ratification_ref?: string;
  /**
   * Pointer to the dispositioned-exception record (REI: justification + owner + review date); required when status=EXCEPTION
   */
  disposition_ref?: string;
  /**
   * Typed pointers to backing artifacts — pointers, never payloads
   */
  evidence_refs: string[];
};
