/* eslint-disable */
/**
 * AUTO-GENERATED by web/scripts/codegen.mjs from schemas/ontology/verdict.schema.json —
 * do not edit; run `npm run codegen` after a schema change.
 */

export type ExceptionDispositionRef = string | null;
export type Message = string | null;
export type RatificationRef = string | null;
export type VerdictState = "PASS" | "FAIL" | "UNKNOWN" | "EXCLUDED" | "EXCEPTION";
export type UnknownWhy =
  "UNKNOWN_DISCOVERY" | "UNKNOWN_OWNER" | "UNKNOWN_POPULATION" | "UNKNOWN_EVIDENCE" | "UNKNOWN_TESTABILITY";

/**
 * The five ratified states (D-V1), never interchangeable. UNKNOWN
 * carries a why-code (D-U1); EXCLUDED carries its ratification;
 * EXCEPTION carries its disposition.
 */
export interface Verdict {
  exception_disposition_ref?: ExceptionDispositionRef;
  message?: Message;
  ratification_ref?: RatificationRef;
  state: VerdictState;
  unknown_why?: UnknownWhy | null;
}
