#!/usr/bin/env node
/**
 * C1 — TypeScript codegen from the committed JSON Schemas.
 *
 * Mirrors the Python side's discipline (scripts/generate_schemas.py +
 * tests/test_schema_drift.py): generate → commit → assert byte-identity.
 * Default mode writes web/src/data/__generated__/; `--check` regenerates
 * into a tempdir and byte-compares, exiting 1 with a diff so CI and
 * scripts/verify-web.sh fail on drift.
 *
 * The roster is explicit — a schema added to schemas/ does not silently
 * start generating; adding it here is a reviewed act. Determinism comes
 * from the exact-pinned json-schema-to-typescript version plus the
 * committed bytes.
 */

import { compileFromFile } from "json-schema-to-typescript";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const WEB_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const REPO_ROOT = path.dirname(WEB_ROOT);
const OUT_DIR = path.join(WEB_ROOT, "src", "data", "__generated__");

/** schema file (repo-relative) -> generated module basename. */
const ROSTER = [
  ["schemas/verdict-record.schema.json", "verdict-record.ts"],
  ["schemas/ontology/verdict.schema.json", "verdict.ts"],
  ["schemas/ontology/delta.schema.json", "delta.ts"],
  ["schemas/ontology/population.schema.json", "population.ts"],
  ["schemas/ontology/assertion.schema.json", "assertion.ts"],
  ["schemas/ontology/capability_entry.schema.json", "capability-entry.ts"],
];

const banner = (schemaRel) =>
  `/* eslint-disable */\n/**\n * AUTO-GENERATED by web/scripts/codegen.mjs from ${schemaRel} —\n * do not edit; run \`npm run codegen\` after a schema change.\n */`;

async function generate(destDir) {
  await mkdir(destDir, { recursive: true });
  const outputs = [];
  for (const [schemaRel, outName] of ROSTER) {
    const schemaPath = path.join(REPO_ROOT, schemaRel);
    const ts = await compileFromFile(schemaPath, {
      cwd: path.dirname(schemaPath),
      bannerComment: banner(schemaRel),
      additionalProperties: false,
    });
    const outPath = path.join(destDir, outName);
    await writeFile(outPath, ts);
    outputs.push(outName);
  }
  return outputs;
}

async function check() {
  const tmp = await mkdtemp(path.join(tmpdir(), "aegis-codegen-"));
  await generate(tmp);
  let drifted = 0;
  for (const [, outName] of ROSTER) {
    const fresh = await readFile(path.join(tmp, outName), "utf8");
    let committed = null;
    try {
      committed = await readFile(path.join(OUT_DIR, outName), "utf8");
    } catch {
      // missing committed file counts as drift
    }
    if (committed !== fresh) {
      drifted += 1;
      console.error(`codegen drift: src/data/__generated__/${outName} — run \`npm run codegen\``);
      if (committed !== null) {
        const a = committed.split("\n");
        const b = fresh.split("\n");
        for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
          if (a[i] !== b[i]) {
            console.error(`  first divergence at line ${i + 1}:`);
            console.error(`    committed: ${a[i] ?? "<absent>"}`);
            console.error(`    fresh:     ${b[i] ?? "<absent>"}`);
            break;
          }
        }
      } else {
        console.error("  committed file is missing");
      }
    }
  }
  if (drifted > 0) process.exit(1);
  console.log(`codegen:check — ${ROSTER.length} generated modules match committed bytes`);
}

if (process.argv.includes("--check")) {
  await check();
} else {
  const outputs = await generate(OUT_DIR);
  console.log(`codegen — wrote ${outputs.length} modules to src/data/__generated__/`);
}
