#!/usr/bin/env node
/* Generate TypeScript types from the backend's exported JSON Schemas.
 *
 * Source of truth: ../schemas/*.schema.json (pydantic v2 export, committed
 * by scripts/export_schemas.py and kept current by
 * tests/schema/test_generated_schemas_current.py). Output goes to
 * src/lib/types/generated/ and is COMMITTED; CI re-runs this script and
 * fails on `git diff` (web-verify "codegen drift"). Assignability between
 * these generated types and the hand-mirrored ontology types is enforced
 * by src/lib/types/checks.ts — ontology drift fails `tsc`.
 */

import { compileFromFile } from "json-schema-to-typescript";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = resolve(here, "..", "..", "schemas");
const outDir = resolve(here, "..", "src", "lib", "types", "generated");

/** Schemas the frontend renders (kebab name = schema file stem). */
const SCHEMAS = [
  "population",
  "claim",
  "assertion",
  "verdict-record",
  "evidence-quality-contract",
  "capability-entry",
  "disposition",
  "compile-error",
];

const banner = (name) =>
  `/* AUTO-GENERATED by scripts/codegen-types.mjs from schemas/${name}.schema.json.\n` +
  ` * Do not edit by hand — regenerate with \`npm run codegen\`. */\n`;

mkdirSync(outDir, { recursive: true });

// kebab-case → PascalCase namespace (schema modules share member names,
// so the barrel re-exports each module under its own namespace).
const pascal = (name) =>
  name
    .split("-")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");

const exports_ = [];
for (const name of SCHEMAS) {
  const file = join(schemasDir, `${name}.schema.json`);
  const ts = await compileFromFile(file, {
    bannerComment: banner(name),
    cwd: schemasDir,
    additionalProperties: false,
    style: { printWidth: 90 },
  });
  writeFileSync(join(outDir, `${name}.ts`), ts);
  exports_.push(`export * as ${pascal(name)}Schema from "./${name}";`);
  console.log(`codegen: ${name}.schema.json → generated/${name}.ts`);
}

writeFileSync(
  join(outDir, "index.ts"),
  "/* AUTO-GENERATED barrel — see scripts/codegen-types.mjs. */\n" +
    exports_.join("\n") +
    "\n"
);
console.log(`codegen: wrote ${SCHEMAS.length} module(s) + index.ts`);
