#!/usr/bin/env node
/* Generate TypeScript types from the backend's exported JSON Schemas.
 *
 * Source of truth: ../../schemas/**\/*.schema.json (pydantic v2 export,
 * committed by scripts/export_schemas.py). Output goes to
 * src/lib/types/generated/ and is COMMITTED; `--check` regenerates into a
 * tempdir and byte-compares, exiting 1 with a diff so CI and
 * scripts/verify-web.sh fail on drift (mirrors the Python side's
 * generate → commit → assert-byte-identity discipline). Assignability
 * between these generated types and the hand-mirrored ontology/artifact
 * types is enforced by src/lib/types/checks.ts — ontology drift fails
 * `tsc`.
 *
 * `compile-error` carries no backend schema (TYP01 E-codes are compiler
 * output text, never a pydantic model) and is deliberately absent from
 * this roster — it stays local-only/unchecked in src/lib/types/artifacts.ts.
 */

import { compileFromFile } from "json-schema-to-typescript";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = resolve(here, "..", "..", "schemas");
const outDir = resolve(here, "..", "src", "lib", "types", "generated");

/** kebab output name -> schema file, relative to schemasDir. The roster is
 * explicit — a schema added under schemas/ does not silently start
 * generating; adding it here is a reviewed act. */
const SCHEMAS = [
  ["population", "ontology/population.schema.json"],
  ["claim", "ontology/claim.schema.json"],
  ["assertion", "ontology/assertion.schema.json"],
  ["verdict", "ontology/verdict.schema.json"],
  ["verdict-record", "verdict-record.schema.json"],
  ["delta", "ontology/delta.schema.json"],
  ["evidence-quality-contract", "ontology/evidence_quality_contract.schema.json"],
  ["capability-entry", "ontology/capability_entry.schema.json"],
  ["disposition", "ontology/disposition_record.schema.json"],
];

const banner = (schemaRel) =>
  `/* AUTO-GENERATED by scripts/codegen-types.mjs from schemas/${schemaRel}.\n` +
  ` * Do not edit by hand — regenerate with \`npm run codegen\`. */\n`;

// kebab-case → PascalCase namespace (schema modules share member names,
// so the barrel re-exports each module under its own namespace).
const pascal = (name) =>
  name
    .split("-")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");

async function generate(destDir) {
  await mkdir(destDir, { recursive: true });
  const exports_ = [];
  for (const [name, schemaRel] of SCHEMAS) {
    const file = join(schemasDir, schemaRel);
    const ts = await compileFromFile(file, {
      bannerComment: banner(schemaRel),
      cwd: dirname(file),
      additionalProperties: false,
      style: { printWidth: 90 },
    });
    await writeFile(join(destDir, `${name}.ts`), ts);
    exports_.push(`export * as ${pascal(name)}Schema from "./${name}";`);
  }
  await writeFile(
    join(destDir, "index.ts"),
    "/* AUTO-GENERATED barrel — see scripts/codegen-types.mjs. */\n" +
      exports_.join("\n") +
      "\n"
  );
  return exports_.length;
}

async function check() {
  const tmp = await mkdtemp(join(tmpdir(), "aegis-web-codegen-"));
  await generate(tmp);
  let drifted = 0;
  const names = [...SCHEMAS.map(([name]) => name), "index"];
  for (const name of names) {
    const fresh = await readFile(join(tmp, `${name}.ts`), "utf8");
    let committed = null;
    try {
      committed = await readFile(join(outDir, `${name}.ts`), "utf8");
    } catch {
      // missing committed file counts as drift
    }
    if (committed !== fresh) {
      drifted += 1;
      console.error(`codegen drift: src/lib/types/generated/${name}.ts — run \`npm run codegen\``);
    }
  }
  if (drifted > 0) process.exit(1);
  console.log(`codegen:check — ${names.length} generated module(s) match committed bytes`);
}

if (process.argv.includes("--check")) {
  await check();
} else {
  const count = await generate(outDir);
  console.log(`codegen: wrote ${count} module(s) + index.ts to src/lib/types/generated/`);
}
