import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // src/lib/types/generated/** is AUTO-GENERATED by scripts/codegen-types.mjs
    // from schemas/**/*.schema.json (json-schema-to-typescript output) — not
    // hand-authored, and off-limits to edit per that script's own header.
    ignores: [".next/**", "out/**", "build/**", "next-env.d.ts", "src/lib/types/generated/**"],
  },
];

export default eslintConfig;
